name: phyluce
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _r-mutex=1.0.1
  - abyss=1.5.2
  - argcomplete=1.10.0
  - bcftools=1.8
  - bedtools=2.29.0
  - binutils_impl_linux-64=2.31.1
  - binutils_linux-64=2.31.1
  - biopython=1.74
  - blas=2.12
  - bowtie=1.2.3
  - bwa=0.7.17
  - bwidget=1.9.11
  - bx-python=0.8.4
  - bzip2=1.0.8
  - ca-certificates=2019.9.11
  - cairo=1.16.0
  - certifi=2019.9.11
  - collectl=4.0.4
  - curl=7.65.3
  - dendropy=3.12.3
  - fastool=0.1.4
  - fontconfig=2.13.1
  - freetype=2.10.0
  - fribidi=1.0.5
  - gatk=3.8
  - gawk=5.0.1
  - gblocks=0.91b
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - glib=2.58.3
  - graphite2=1.3.13
  - grep=2.14
  - gsl=2.5
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - harfbuzz=2.4.0
  - htslib=1.7
  - icu=64.2
  - illumiprocessor=2.0.9
  - itero=1.1.2
  - java-jdk=7.0.91
  - jellyfish=0.6.1
  - jpeg=9c
  - krb5=1.16.3
  - lastz=1.0.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.65.3
  - libdeflate=1.3
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc=7.2.0
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libssh2=1.8.2
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - lz4-c=1.8.3
  - lzo=2.10
  - mafft=7.407
  - make=4.2.1
  - mpi=1.0
  - mpi4py=3.0.2
  - muscle=3.8.1551
  - ncurses=6.1
  - nomkl=3.0
  - numpy=1.16.4
  - openjdk=8.0.192
  - openmpi=4.0.1
  - openssl=1.1.1c
  - pandas=0.24.2
  - pango=1.42.4
  - parafly=r2013_01_21
  - pcre=8.41
  - perl=5.26.2
  - perl-threaded=5.26.0
  - phyluce=1.6.7
  - picard=2.20.8
  - pip=19.2.3
  - pixman=0.38.0
  - pthread-stubs=0.4
  - pysam=0.14.1
  - python=2.7.15
  - python-dateutil=2.8.0
  - python-lzo=1.12
  - pytz=2019.2
  - pyvcf=0.6.8
  - r-assertthat=0.2.1
  - r-backports=1.1.4
  - r-base=3.6.1
  - r-bitops=1.0_6
  - r-catools=1.17.1.2
  - r-cli=1.1.0
  - r-colorspace=1.4_1
  - r-crayon=1.3.4
  - r-digest=0.6.20
  - r-ellipsis=0.2.0.1
  - r-fansi=0.4.0
  - r-gdata=2.18.0
  - r-ggplot2=3.2.1
  - r-glue=1.3.1
  - r-gplots=3.0.1.1
  - r-gsalib=2.1
  - r-gtable=0.3.0
  - r-gtools=3.8.1
  - r-kernsmooth=2.23_15
  - r-labeling=0.3
  - r-lattice=0.20_38
  - r-lazyeval=0.2.2
  - r-magrittr=1.5
  - r-mass=7.3_51.4
  - r-matrix=1.2_17
  - r-mgcv=1.8_28
  - r-munsell=0.5.0
  - r-nlme=3.1_141
  - r-pillar=1.4.2
  - r-pkgconfig=2.0.2
  - r-plyr=1.8.4
  - r-r6=2.4.0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.2
  - r-reshape=0.8.8
  - r-reshape2=1.4.3
  - r-rlang=0.4.0
  - r-scales=1.0.0
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-tibble=2.1.3
  - r-utf8=1.1.4
  - r-vctrs=0.2.0
  - r-viridislite=0.3.0
  - r-withr=2.1.2
  - r-zeallot=0.1.0
  - raxml=8.2.12
  - readline=8.0
  - samtools=1.6
  - schwimmbad=0.3.0
  - sed=4.7
  - seqtk=1.3
  - setuptools=41.2.0
  - six=1.12.0
  - slclust=02022010
  - spades=3.12.0
  - sqlite=3.29.0
  - tbb=2019.8
  - tk=8.6.9
  - tktable=2.10
  - trimal=1.4.1
  - trimmomatic=0.39
  - trinity=2.1.1
  - velvet=1.2.10
  - wheel=0.33.6
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.8
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.4.0
