[tool.poetry]
name = "uceasy"
version = "2.0.0-a0"
description = "Wrapper for the Phyluce phylogenomics software package"
authors = ["Caio Raposo <caioraposo@protonmail.com>"]
license = "MIT"

[tool.black]
line-length = 90
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^0.25.0"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
pytest-mock = "^1.10"
black = {version = "^18.3-alpha.0", allow-prereleases = true}
pre-commit = "^1.18"
nox = "^2019.11.9"
coverage = {extras = ["toml"], version = "^5.0.3"}
pytest-cov = "^2.8.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

