version: 2
jobs:
  build:
    machine: true
    environment:
        PATH: $PATH:~/miniconda/bin
    steps:
      - checkout
      - run:
          name: Download and install conda
          command:
              wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
              bash miniconda.sh -b -p $HOME/miniconda
              hash -r
              conda config --set always_yes yes --set changeps1 no
              conda update -q conda
              # Useful for debugging any issues with conda
              conda info -a
      - run:
          name: Configure bioconda and install phyluce
          command: |
              conda config --add channels defaults
              conda config --add channels bioconda
              conda config --add channels conda-forge
              conda create -n phyluce phyluce jellyfish=2.2.3
              conda activate phyluce

              python setup.py develop
              pip install -r requirements.txt
              
      - run:
          command: | # Download test dataset
              wget -o fastq.zip https://ndownloader.figshare.com/articles/1284521/versions/1
              unzip fastq.zip -o tests/raw_fastq
      - run:
          command: |
              pytest tests/test_env_manager.py
              pytest tests/test_quality_control.py

    branches:
      only:
        - dev
