version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
             
      - run:
          command: |
              conda config --set always_yes yes
              conda config --add channels conda-forge
              conda config --add channels bioconda
              conda create -n phyluce phyluce
              conda init bash

      - run:
          name: Download test dataset
          command: |
              pip install poetry==0.12.17
              poetry install --no-interaction --no-ansi -v
      - run:
          shell: /bin/bash -il
          command: |
              conda activate phyluce
              mkdir tests/output
              poetry run pytest tests/

    branches:
      only:
        - dev
