name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64
    - name: Install poetry and nox
      run: |
        pip install nox==2019.11.9
        pip install poetry==1.0.5
    - name: Install Phyluce
      run: conda env create --file phyluce-environment.yaml
    - name: Run coverage
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate phyluce
        nox --sessions tests-3.8 coverage
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
