name: Tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches_ignore: []

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Linting
        run: |
          pip install pre-commit
          pre-commit run --all-files

  Linux:
    runs-on: ubuntu-latest
    needs: Linting
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64
    - name: Install Poetry and nox
      run: |
          pip install poetry==1.0.0
          pip install nox==2019.11.9
    - name: Install Phyluce
      run: conda env create --file phyluce-environment.yaml
    - name: Test
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate phyluce
        nox
